"""CSV file name -> table name. Explicit on purpose: a new upstream table is a deliberate change."""

TABLES: dict[str, str] = {
    "AllstarFull.csv": "allstar_full",
    "Appearances.csv": "appearances",
    "AwardsManagers.csv": "awards_managers",
    "AwardsPlayers.csv": "awards_players",
    "AwardsShareManagers.csv": "awards_share_managers",
    "AwardsSharePlayers.csv": "awards_share_players",
    "Batting.csv": "batting",
    "BattingPost.csv": "batting_post",
    "CollegePlaying.csv": "college_playing",
    "Fielding.csv": "fielding",
    "FieldingOF.csv": "fielding_of",
    "FieldingOFsplit.csv": "fielding_of_split",
    "FieldingPost.csv": "fielding_post",
    "HallOfFame.csv": "hall_of_fame",
    "HomeGames.csv": "home_games",
    "Managers.csv": "managers",
    "ManagersHalf.csv": "managers_half",
    "Parks.csv": "parks",
    "People.csv": "people",
    "Pitching.csv": "pitching",
    "PitchingPost.csv": "pitching_post",
    "Salaries.csv": "salaries",
    "Schools.csv": "schools",
    "SeriesPost.csv": "series_post",
    "Teams.csv": "teams",
    "TeamsFranchises.csv": "teams_franchises",
    "TeamsHalf.csv": "teams_half",
}
